// src/components/QueryInput.tsx
import React from "react";
import { useDB } from "../context/DBContext";
import { generateSQL, runSQL } from "../utils/api";
import { toast } from "sonner";
import Loader from "./Loader";

export const QueryInput: React.FC<{
  onResult: (sql: string, columns: string[], rows: any[][]) => void;
}> = ({ onResult }) => {
  const { connection } = useDB();
  const [query, setQuery] = React.useState("");
  const [loading, setLoading] = React.useState(false);

  const normalizeExecResult = (execResp: any) => {
    // backend returns either:
    // - { columns: [...], results: [{...}, {...}] }  (RealDictCursor)
    // - { results: [[...], [...]], columns: [...] } (row arrays)
    // - { rowcount: n, message: "..."} for non-SELECT w/o RETURNING
    let columns: string[] = [];
    let rows: any[][] = [];

    if (!execResp) return { columns, rows };

    // If results are array of objects (RealDictCursor)
    if (Array.isArray(execResp.results) && execResp.results.length && typeof execResp.results[0] === "object" && !Array.isArray(execResp.results[0])) {
      const results = execResp.results as Record<string, any>[];
      const keys = execResp.columns && execResp.columns.length ? execResp.columns : Array.from(results.length ? Object.keys(results[0]) : []);
      columns = keys;
      rows = results.map((r) => keys.map((k) => r[k]));
      return { columns, rows };
    }

    // If results are array of arrays and columns provided
    if (Array.isArray(execResp.results) && execResp.results.length && Array.isArray(execResp.results[0])) {
      columns = execResp.columns ?? execResp.columns ?? execResp.columns ?? [];
      rows = execResp.results;
      return { columns, rows };
    }

    // If non-select that returned rowcount / message only
    if (execResp.rowcount !== undefined && (!execResp.results || execResp.results.length === 0)) {
      // present a one-row summary to UI
      columns = ["message", "rowcount"];
      rows = [[execResp.message ?? "OK", execResp.rowcount]];
      return { columns, rows };
    }

    // fallback: nothing to show
    return { columns, rows };
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!connection.connected) {
      toast.error("Please connect to the database first");
      return;
    }
    if (!query.trim()) return;

    setLoading(true);
    try {
      // 1) Generate SQL using server-side session (token)
      //    generateSQL will use saved session token; we pass only nl_query
      const genResp = await generateSQL({ nl_query: query });
      const sql = genResp.sql?.trim() ?? "";

      if (!sql) {
        // In case an older backend returned rows directly in generateSQL (legacy)
        // genResp might include columns+rows already (but our modern flow returns only sql)
        if (genResp.columns?.length || genResp.rows?.length) {
          onResult(genResp.sql ?? "", genResp.columns ?? [], genResp.rows ?? []);
          if (!(genResp.columns?.length)) toast("No rows returned");
          setLoading(false);
          return;
        }
        throw new Error("No SQL was generated by the backend");
      }

      // 2) Execute the generated SQL on server using runSQL (uses session token)
      const execResp = await runSQL(sql);

      // 3) Normalize results to columns + rows[][] and call onResult
      const { columns, rows } = normalizeExecResult(execResp);
      onResult(sql, columns, rows);

      if (!columns?.length || !rows?.length) {
        toast.success(execResp.message ?? "Query executed — no rows returned");
      }
    } catch (err: any) {
      // Prominent error message to user
      const msg = err?.detail ?? err?.message ?? String(err);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={submit} className="rounded-xl border bg-card p-4 shadow-sm">
      <div className="mb-2 flex items-center justify-between">
        <h2 className="text-base font-semibold">Natural Language Query</h2>
        <span className="text-xs text-muted-foreground">
          Connected: {connection.connected ? "Yes" : "No"}
        </span>
      </div>

      <textarea
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="e.g. Show the top 10 customers by revenue last quarter"
        className="min-h-[140px] w-full rounded-md border bg-background p-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
      />

      <div className="mt-3 flex items-center justify-end">
        <button
          type="submit"
          disabled={loading || !connection.connected}
          className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-95 disabled:opacity-60"
        >
          {loading ? <Loader label="Generating" /> : "Generate & Run"}
        </button>
      </div>
    </form>
  );
};

export default QueryInput;
